from typing import Protocol, List
from app.domain.entities.run_history import RunHistory
from app.domain.entities.run_step_record import RunStepRecord

class RunHistoryRepository(Protocol):
    def create_run(self, run: RunHistory) -> RunHistory:
        ...
    def update_run(self, run: RunHistory) -> None:
        ...
    def append_step_record(self, record: RunStepRecord) -> RunStepRecord:
        ...
    def list_by_flow(self, flow_id: int) -> List[RunHistory]:
        ...
