version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - local_pg_data:/var/lib/postgresql/data

volumes:
  local_pg_data:
