"""create core tables

Revision ID: de549a729e53
Revises: 
Create Date: 2025-10-05 02:16:33.584865+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de549a729e53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=200), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flows_alias'), ['alias'], unique=True)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('python_version', sa.String(length=20), nullable=True),
    sa.Column('env_vars', sa.JSON(), nullable=False),
    sa.Column('path_entries', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_name'), ['name'], unique=True)

    op.create_table('flow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('artifact_ref', sa.String(length=500), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('env', sa.JSON(), nullable=True),
    sa.Column('working_dir', sa.String(length=500), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('ref_alias', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'order', name='uq_flow_order')
    )
    with op.batch_alter_table('flow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_steps_flow_id'), ['flow_id'], unique=False)

    op.create_table('run_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_history_flow_id'), ['flow_id'], unique=False)

    op.create_table('run_step_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_path', sa.String(length=500), nullable=True),
    sa.Column('stderr_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_step_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_step_records_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_step_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_step_records_run_id'))

    op.drop_table('run_step_records')
    with op.batch_alter_table('run_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_history_flow_id'))

    op.drop_table('run_history')
    with op.batch_alter_table('flow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_steps_flow_id'))

    op.drop_table('flow_steps')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_name'))

    op.drop_table('profiles')
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flows_alias'))

    op.drop_table('flows')
    # ### end Alembic commands ###
