"""init_schemas

Revision ID: 5599371da9fb
Revises: 
Create Date: 2025-11-15 17:38:02.101506

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from apps.infrastructure.database.base import GUID

# revision identifiers, used by Alembic.
revision: str = '5599371da9fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('purpose', sa.String(), nullable=True),
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('virtual_environments',
                    sa.Column('profile_id', GUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('manager', sa.String(), nullable=False),
                    sa.Column('python_version', sa.String(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_environments')
    op.drop_table('profiles')
    # ### end Alembic commands ###
