"""init_schema

Revision ID: 585c4b930d40
Revises: 
Create Date: 2025-12-08 11:13:41.567372

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from apps.infrastructure.database.base import GUID

# revision identifiers, used by Alembic.
revision: str = '585c4b930d40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('purpose', sa.String(), nullable=True),
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('virtual_environments',
                    sa.Column('profile_id', GUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('manager', sa.String(), nullable=False),
                    sa.Column('python_version', sa.String(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('dependency',
                    sa.Column('environment_id', GUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['environment_id'], ['virtual_environments.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency')
    op.drop_table('virtual_environments')
    op.drop_table('profiles')
    # ### end Alembic commands ###
