from typing import Protocol, List
from uuid import UUID
from apps.modules.virtual_environment.domain.entities.virtual_environment_entity import VirtualEnvironmentEntity


class VirtualEnvironmentRepositoryInterface(Protocol):
    def create(self, environment: VirtualEnvironmentEntity) -> None: ...
    def list_paginated(self, offset: int, limit: int) -> List[VirtualEnvironmentEntity]: ...
    def get_by_id(self, environment_id: UUID) -> VirtualEnvironmentEntity | None: ...
    def update(self, environment: VirtualEnvironmentEntity) -> None: ...
    def delete(self, environment: VirtualEnvironmentEntity) -> None: ...
    def exists(self, environment_id: UUID) -> bool: ...
