from typing import Protocol, TypeVar, List
from uuid import UUID

Entity = TypeVar("Entity")


class BaseRepositoryInterface(Protocol[Entity]):
    def create(self, entity: Entity) -> None: ...

    def list_paginated(self, offset: int, limit: int) -> List[Entity]: ...

    def get_by_id(self, entity_id: UUID) -> Entity | None: ...

    def update(self, entity: Entity) -> None: ...

    def delete(self, entity: Entity) -> None: ...

    def exists(self, entity_id: UUID) -> bool: ...
